// LOADERS
export const LOADING_SIGN_UP = "LOADING_SIGN_UP";
export const LOADING_LOGIN = "LOADING_LOGIN";
export const LOADING_ADD_PRODUCT = "LOADING_ADD_PRODUCT";
export const LOADING_PRODUCTS = "LOADING_PRODUCTS";
export const LOADING_COMMENTS = "LOADING_COMMENTS";
export const LOADING_USER = "LOADING_USER";

// ERRORS
export const SET_ERRORS_LOGIN = "SET_ERRORS_LOGIN";
export const SET_ERRORS_SIGNUP = "SET_ERRORS_SIGNUP";
export const SET_SUCCESS_ADD_PRODUCT = "SET_SUCCESS_ADD_PRODUCT";
export const SET_ERRORS_ADD_PRODUCT = "SET_ERRORS_ADD_PRODUCT";
export const CLEAR_ERRORS_ADD_PRODUCT = "CLEAR_ERRORS_ADD_PRODUCT";

// USER
export const SET_AUTH_USER = "SET_AUTH_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const SET_AUTHENTICATED = "SET_AUTHENTICATED";
export const SET_UNAUTHENTICATED = "SET_UNAUTHENTICATED";
export const TOGGLE_LIKE_PRODUCT = "TOGGLE_LIKE_PRODUCT";
export const UPDATE_USER_INFO = "UPDATE_USER_INFO";
export const DELETE_ACCOUNT = "DELETE_ACCOUNT";
export const SET_FOLLOWING = "SET_FOLLOWING";
export const SET_FOLLOWERS = "SET_FOLLOWERS";
export const SET_BLOCK_USER = "SET_BLOCK_USER";
export const SET_UNBLOCK_USER = "SET_UNBLOCK_USER";

// DATA
export const SET_PRODUCTS = "SET_PRODUCTS";
export const SET_SINGLE_PRODUCT = "SET_SINGLE_PRODUCT";
export const CLEAR_PRODUCTS = "CLEAR_PRODUCTS";
export const CLEAR_FAV_PRODUCTS = "CLEAR_FAV_PRODUCTS";
export const SET_FAV_PRODUCTS = "SET_FAV_PRODUCTS";
export const SET_USER_DATA = "SET_USER_DATA";
export const DELETE_PRODUCT = "DELETE_PRODUCT";

// COMMENTS
export const SET_COMMENTS = "SET_COMMENTS";
export const ADD_COMMENT = "ADD_COMMENT";
export const DELETE_COMMENT = "DELETE_COMMENT";
export const EDIT_COMMENT = "EDIT_COMMENT";

// MESSAGES
export const ADD_MESSAGE = "ADD_MESSAGE";
export const SET_CONVERSATIONS_ROOMS = "SET_CONVERSATIONS_ROOMS";
export const SET_MESSAGES = "SET_MESSAGES";
export const SET_UNREAD_MESSAGES = "SET_UNREAD_MESSAGES";
export const DELETE_MESSAGE = "DELETE_MESSAGE";
// NOTIFICATIONS
export const SET_NOTIFICATIONS = "SET_NOTIFICATIONS";
export const CLEAR_UNREAD_NOTIFICATIONS = "CLEAR_UNREAD_NOTIFICATIONS";
export const SET_NOTIFICATION_READ = "SET_NOTIFICATION_READ";

// SHOPPING LIST
export const ADD_SHOPPING_LIST = "ADD_SHOPPING_LIST";
export const REMOVE_SHOPPING_LIST = "REMOVE_SHOPPING_LIST";
