// LOADERS
export const LOADING_SIGN_UP = "LOADING_SIGN_UP";
export const LOADING_LOGIN = "LOADING_LOGIN";
export const LOADING_ADD_PRODUCT = "LOADING_ADD_PRODUCT";
export const LOADING_PRODUCTS = "LOADING_PRODUCTS";
export const LOADING_COMMENTS = "LOADING_COMMENTS";

// ERRORS
export const SET_ERRORS_LOGIN = "SET_ERRORS_LOGIN";
export const SET_ERRORS_SIGNUP = "SET_ERRORS_SIGNUP";
export const SET_SUCCESS_ADD_PRODUCT = "SET_SUCCESS_ADD_PRODUCT";
export const SET_ERRORS_ADD_PRODUCT = "SET_ERRORS_ADD_PRODUCT";
export const CLEAR_ERRORS_ADD_PRODUCT = "CLEAR_ERRORS_ADD_PRODUCT";

// USER
export const SET_AUTH_USER = "SET_AUTH_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const SET_AUTHENTICATED = "SET_AUTHENTICATED";
export const SET_UNAUTHENTICATED = "SET_UNAUTHENTICATED";
export const TOGGLE_LIKE_PRODUCT = "TOGGLE_LIKE_PRODUCT";
export const LOADING_USER = "LOADING_USER";

// DATA
export const SET_PRODUCTS = "SET_PRODUCTS";
export const SET_SINGLE_PRODUCT = "SET_SINGLE_PRODUCT";
export const CLEAR_PRODUCTS = "CLEAR_PRODUCTS";
export const CLEAR_FAV_PRODUCTS = "CLEAR_FAV_PRODUCTS";
export const SET_FAV_PRODUCTS = "SET_FAV_PRODUCTS";
export const SET_USER_DATA = "SET_USER_DATA";

// COMMENTS
export const SET_COMMENTS = "SET_COMMENTS";
export const ADD_COMMENT = "ADD_COMMENT";
export const DELETE_COMMENT = "DELETE_COMMENT";
