// LOADERS
export const LOADING_SIGN_UP = "LOADING_SIGN_UP";
export const LOADING_LOGIN = "LOADING_LOGIN";
export const LOADING_ADD_PRODUCT = "LOADING_ADD_PRODUCT";

// ERRORS
export const SET_ERRORS_LOGIN = "SET_ERRORS_LOGIN";
export const SET_ERRORS_SIGNUP = "SET_ERRORS_SIGNUP";
export const SET_SUCCESS_ADD_PRODUCT = "SET_SUCCESS_ADD_PRODUCT";
export const SET_ERRORS_ADD_PRODUCT = "SET_ERRORS_ADD_PRODUCT";
export const CLEAR_ERRORS_ADD_PRODUCT = "CLEAR_ERRORS_ADD_PRODUCT";

// USER
export const SET_USER = "SET_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const SET_AUTHENTICATED = "SET_AUTHENTICATED";
export const SET_UNAUTHENTICATED = "SET_UNAUTHENTICATED";
